#!/bin/bash
systemctl daemon-reload
echo "Enabling Edged daemon service."
if [[ -f "/lib/systemd/system/edged.service" ]]; then
	systemctl enable edged.service
fi
echo "Enabling Supernoded daemon service."
if [[ -f "/lib/systemd/system/supernoded.service" ]]; then
	systemctl enable supernoded.service
fi
