#!/bin/bash
echo "Shutting down Edged daemon service."
if [[ -f "/lib/systemd/system/edged.service" ]] || [[ -f "/etc/systemd/system/edged.service" ]]; then
	systemctl stop edged
fi
echo "Shutting down Supernoded daemon service."
if [[ -f "/lib/systemd/system/supernoded.service" ]] || [[ -f "/etc/systemd/system/supernoded.service" ]]; then
	systemctl stop supernoded
fi
